### ISSUE TITLE
ACTION_DRAG_ENDED Called Twice

### ISSUE THREAD

**Issue by devunwired** [doffm/android-dragarea#1]
Drag events that end, but do not result in ACTION_DROP (meaning the drag event ended but was not inside the bounds of the particular OnDragListener) end up calling the listener with ACTION_DRAG_ENDED twice.

The first seems to be a result of dragDropped() calling onUpEvent() and returning the ACTION_DRAG_ENDED event code.
The second seems to be a result of dragAborted() being called by the touch intercept in DragArea.

One suggestion to fix this is would be to rewrite dragDropped() as follows:

```
private void dragDropped()
{
  for (Droppable d: mDroppables.values())
  {
    boolean hit = isHit(d, (int) mX, (int) mY);
    int event = d.onUpEvent(hit);
    if(event == DragEvent.ACTION_DROP) {
      //Only post event if this is a valid drop
      DragEvent dragEvent = new DragEvent(mDragBundle, event, (int) mX, (int) mY);
      d.listener.onDrag(d.view, dragEvent);
    }
  }
  invalidate();
}
```

Thanks!

**Comment by doffm** [comment]
Thanks for the fix devunwired, I guess DRAG_ENDED twice wasn't a problem for me. After a bit of looking around used your code verbatim.
